# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbls', '0004_auto_20170401_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rbllist',
            name='url',
            field=models.URLField(max_length=100, unique=True),
        ),
    ]
